import { Recipe } from '../api/types';

export const dummyRecipes: Recipe[] = [
  {
    id: '1',
    name: 'Classic Margherita Pizza',
    description: 'A traditional Italian pizza with fresh tomatoes, mozzarella, and basil',
    image: undefined,
    cookTime: 15,
    prepTime: 30,
    servings: 4,
    difficulty: 'medium',
    category: 'Dinner',
    ingredients: [
      { id: '1', name: 'Pizza dough', amount: '1', unit: 'ball' },
      { id: '2', name: 'Tomato sauce', amount: '1/2', unit: 'cup' },
      { id: '3', name: 'Fresh mozzarella', amount: '8', unit: 'oz' },
      { id: '4', name: 'Fresh basil leaves', amount: '10-12', unit: 'leaves' },
      { id: '5', name: 'Olive oil', amount: '2', unit: 'tbsp' },
      { id: '6', name: 'Salt', amount: '1', unit: 'tsp' },
      { id: '7', name: 'Black pepper', amount: '1/2', unit: 'tsp' },
    ],
    steps: [
      {
        id: '1',
        stepNumber: 1,
        description: 'Preheat oven to 500°F (260°C) with a pizza stone or steel',
        duration: 30,
      },
      {
        id: '2',
        stepNumber: 2,
        description: 'Roll out the pizza dough on a floured surface to 12-inch diameter',
        duration: 5,
      },
      {
        id: '3',
        stepNumber: 3,
        description: 'Spread tomato sauce evenly over the dough, leaving a 1-inch border',
        duration: 2,
      },
      {
        id: '4',
        stepNumber: 4,
        description: 'Tear mozzarella into small pieces and distribute over the sauce',
        duration: 3,
      },
      {
        id: '5',
        stepNumber: 5,
        description: 'Drizzle with olive oil and season with salt and pepper',
        duration: 1,
      },
      {
        id: '6',
        stepNumber: 6,
        description: 'Transfer to pizza stone and bake for 10-12 minutes until crust is golden',
        duration: 12,
      },
      {
        id: '7',
        stepNumber: 7,
        description: 'Remove from oven, top with fresh basil leaves, and serve immediately',
        duration: 2,
      },
    ],
    nutrition: {
      calories: 320,
      protein: 15,
      carbs: 35,
      fat: 12,
      fiber: 2,
      sodium: 680,
    },
    tags: ['Italian', 'Vegetarian', 'Quick'],
    isCustom: false,
  },
  {
    id: '2',
    name: 'Creamy Chicken Alfredo',
    description: 'Rich and creamy pasta with tender chicken and parmesan cheese',
    image: undefined,
    cookTime: 20,
    prepTime: 15,
    servings: 4,
    difficulty: 'easy',
    category: 'Dinner',
    ingredients: [
      { id: '1', name: 'Fettuccine pasta', amount: '1', unit: 'lb' },
      { id: '2', name: 'Chicken breast', amount: '2', unit: 'pieces' },
      { id: '3', name: 'Heavy cream', amount: '2', unit: 'cups' },
      { id: '4', name: 'Parmesan cheese', amount: '1', unit: 'cup' },
      { id: '5', name: 'Butter', amount: '4', unit: 'tbsp' },
      { id: '6', name: 'Garlic', amount: '4', unit: 'cloves' },
      { id: '7', name: 'Salt', amount: '1', unit: 'tsp' },
      { id: '8', name: 'Black pepper', amount: '1/2', unit: 'tsp' },
    ],
    steps: [
      {
        id: '1',
        stepNumber: 1,
        description: 'Cook fettuccine according to package directions until al dente',
        duration: 12,
      },
      {
        id: '2',
        stepNumber: 2,
        description: 'Season chicken with salt and pepper, then cook in a large skillet over medium-high heat',
        duration: 8,
      },
      {
        id: '3',
        stepNumber: 3,
        description: 'Remove chicken and set aside. In the same skillet, melt butter',
        duration: 2,
      },
      {
        id: '4',
        stepNumber: 4,
        description: 'Add minced garlic and cook for 1 minute until fragrant',
        duration: 1,
      },
      {
        id: '5',
        stepNumber: 5,
        description: 'Pour in heavy cream and bring to a simmer',
        duration: 3,
      },
      {
        id: '6',
        stepNumber: 6,
        description: 'Gradually whisk in parmesan cheese until smooth',
        duration: 2,
      },
      {
        id: '7',
        stepNumber: 7,
        description: 'Add cooked pasta and chicken to the sauce, toss to combine',
        duration: 2,
      },
    ],
    nutrition: {
      calories: 580,
      protein: 35,
      carbs: 45,
      fat: 28,
      fiber: 2,
      sodium: 890,
    },
    tags: ['Italian', 'Comfort Food', 'Creamy'],
    isCustom: false,
  },
  {
    id: '3',
    name: 'Chocolate Chip Cookies',
    description: 'Soft and chewy homemade chocolate chip cookies',
    image: undefined,
    cookTime: 12,
    prepTime: 20,
    servings: 24,
    difficulty: 'easy',
    category: 'Dessert',
    ingredients: [
      { id: '1', name: 'All-purpose flour', amount: '2 1/4', unit: 'cups' },
      { id: '2', name: 'Butter', amount: '1', unit: 'cup' },
      { id: '3', name: 'Brown sugar', amount: '3/4', unit: 'cup' },
      { id: '4', name: 'White sugar', amount: '1/2', unit: 'cup' },
      { id: '5', name: 'Eggs', amount: '2', unit: 'large' },
      { id: '6', name: 'Vanilla extract', amount: '2', unit: 'tsp' },
      { id: '7', name: 'Baking soda', amount: '1', unit: 'tsp' },
      { id: '8', name: 'Salt', amount: '1', unit: 'tsp' },
      { id: '9', name: 'Chocolate chips', amount: '2', unit: 'cups' },
    ],
    steps: [
      {
        id: '1',
        stepNumber: 1,
        description: 'Preheat oven to 375°F (190°C)',
        duration: 10,
      },
      {
        id: '2',
        stepNumber: 2,
        description: 'Cream together butter and both sugars until light and fluffy',
        duration: 3,
      },
      {
        id: '3',
        stepNumber: 3,
        description: 'Beat in eggs one at a time, then add vanilla',
        duration: 2,
      },
      {
        id: '4',
        stepNumber: 4,
        description: 'In a separate bowl, whisk together flour, baking soda, and salt',
        duration: 2,
      },
      {
        id: '5',
        stepNumber: 5,
        description: 'Gradually mix dry ingredients into wet ingredients',
        duration: 3,
      },
      {
        id: '6',
        stepNumber: 6,
        description: 'Fold in chocolate chips',
        duration: 1,
      },
      {
        id: '7',
        stepNumber: 7,
        description: 'Drop rounded tablespoons onto ungreased baking sheets',
        duration: 5,
      },
      {
        id: '8',
        stepNumber: 8,
        description: 'Bake for 9-11 minutes until golden brown',
        duration: 11,
      },
    ],
    nutrition: {
      calories: 150,
      protein: 2,
      carbs: 20,
      fat: 7,
      fiber: 1,
      sugar: 12,
      sodium: 120,
    },
    tags: ['Dessert', 'Baking', 'Sweet'],
    isCustom: false,
  },
  {
    id: '4',
    name: 'Grilled Salmon with Lemon',
    description: 'Perfectly grilled salmon with fresh lemon and herbs',
    image: undefined,
    cookTime: 10,
    prepTime: 10,
    servings: 4,
    difficulty: 'easy',
    category: 'Dinner',
    ingredients: [
      { id: '1', name: 'Salmon fillets', amount: '4', unit: 'pieces' },
      { id: '2', name: 'Lemon', amount: '2', unit: 'pieces' },
      { id: '3', name: 'Olive oil', amount: '3', unit: 'tbsp' },
      { id: '4', name: 'Fresh dill', amount: '2', unit: 'tbsp' },
      { id: '5', name: 'Garlic', amount: '3', unit: 'cloves' },
      { id: '6', name: 'Salt', amount: '1', unit: 'tsp' },
      { id: '7', name: 'Black pepper', amount: '1/2', unit: 'tsp' },
    ],
    steps: [
      {
        id: '1',
        stepNumber: 1,
        description: 'Preheat grill to medium-high heat',
        duration: 10,
      },
      {
        id: '2',
        stepNumber: 2,
        description: 'Pat salmon fillets dry and season with salt and pepper',
        duration: 2,
      },
      {
        id: '3',
        stepNumber: 3,
        description: 'Mix olive oil, minced garlic, and chopped dill in a small bowl',
        duration: 2,
      },
      {
        id: '4',
        stepNumber: 4,
        description: 'Brush the herb mixture over the salmon fillets',
        duration: 1,
      },
      {
        id: '5',
        stepNumber: 5,
        description: 'Place salmon on grill, skin-side down, and cook for 4-5 minutes',
        duration: 5,
      },
      {
        id: '6',
        stepNumber: 6,
        description: 'Flip and cook for another 3-4 minutes until fish flakes easily',
        duration: 4,
      },
      {
        id: '7',
        stepNumber: 7,
        description: 'Serve with lemon wedges and fresh dill garnish',
        duration: 1,
      },
    ],
    nutrition: {
      calories: 280,
      protein: 35,
      carbs: 2,
      fat: 15,
      fiber: 0,
      sodium: 320,
    },
    tags: ['Healthy', 'Grilled', 'Seafood'],
    isCustom: false,
  },
  {
    id: '5',
    name: 'Avocado Toast',
    description: 'Simple and delicious avocado toast with various toppings',
    image: undefined,
    cookTime: 5,
    prepTime: 5,
    servings: 2,
    difficulty: 'easy',
    category: 'Breakfast',
    ingredients: [
      { id: '1', name: 'Bread slices', amount: '4', unit: 'slices' },
      { id: '2', name: 'Ripe avocados', amount: '2', unit: 'pieces' },
      { id: '3', name: 'Lemon juice', amount: '1', unit: 'tbsp' },
      { id: '4', name: 'Salt', amount: '1/2', unit: 'tsp' },
      { id: '5', name: 'Black pepper', amount: '1/4', unit: 'tsp' },
      { id: '6', name: 'Red pepper flakes', amount: '1/4', unit: 'tsp' },
      { id: '7', name: 'Olive oil', amount: '1', unit: 'tbsp' },
    ],
    steps: [
      {
        id: '1',
        stepNumber: 1,
        description: 'Toast bread slices until golden brown',
        duration: 3,
      },
      {
        id: '2',
        stepNumber: 2,
        description: 'Cut avocados in half, remove pit, and scoop flesh into a bowl',
        duration: 2,
      },
      {
        id: '3',
        stepNumber: 3,
        description: 'Add lemon juice, salt, and pepper to avocado and mash with a fork',
        duration: 1,
      },
      {
        id: '4',
        stepNumber: 4,
        description: 'Spread avocado mixture evenly on toast',
        duration: 1,
      },
      {
        id: '5',
        stepNumber: 5,
        description: 'Drizzle with olive oil and sprinkle with red pepper flakes',
        duration: 1,
      },
    ],
    nutrition: {
      calories: 220,
      protein: 6,
      carbs: 18,
      fat: 16,
      fiber: 8,
      sodium: 280,
    },
    tags: ['Healthy', 'Quick', 'Vegetarian'],
    isCustom: false,
  },
  {
    id: '6',
    name: 'Beef Stir Fry',
    description: 'Quick and flavorful beef stir fry with vegetables',
    image: undefined,
    cookTime: 15,
    prepTime: 20,
    servings: 4,
    difficulty: 'medium',
    category: 'Dinner',
    ingredients: [
      { id: '1', name: 'Beef sirloin', amount: '1', unit: 'lb' },
      { id: '2', name: 'Broccoli', amount: '2', unit: 'cups' },
      { id: '3', name: 'Bell peppers', amount: '2', unit: 'pieces' },
      { id: '4', name: 'Onion', amount: '1', unit: 'medium' },
      { id: '5', name: 'Garlic', amount: '3', unit: 'cloves' },
      { id: '6', name: 'Ginger', amount: '1', unit: 'tbsp' },
      { id: '7', name: 'Soy sauce', amount: '3', unit: 'tbsp' },
      { id: '8', name: 'Sesame oil', amount: '1', unit: 'tbsp' },
      { id: '9', name: 'Cornstarch', amount: '1', unit: 'tbsp' },
    ],
    steps: [
      {
        id: '1',
        stepNumber: 1,
        description: 'Slice beef thinly against the grain',
        duration: 5,
      },
      {
        id: '2',
        stepNumber: 2,
        description: 'Mix soy sauce, sesame oil, and cornstarch in a bowl',
        duration: 2,
      },
      {
        id: '3',
        stepNumber: 3,
        description: 'Marinate beef in the sauce mixture for 10 minutes',
        duration: 10,
      },
      {
        id: '4',
        stepNumber: 4,
        description: 'Heat a large wok or skillet over high heat',
        duration: 2,
      },
      {
        id: '5',
        stepNumber: 5,
        description: 'Stir-fry beef for 2-3 minutes until browned',
        duration: 3,
      },
      {
        id: '6',
        stepNumber: 6,
        description: 'Add vegetables and stir-fry for 4-5 minutes until crisp-tender',
        duration: 5,
      },
      {
        id: '7',
        stepNumber: 7,
        description: 'Add garlic and ginger, stir-fry for 1 minute',
        duration: 1,
      },
      {
        id: '8',
        stepNumber: 8,
        description: 'Return beef to pan and toss everything together',
        duration: 1,
      },
    ],
    nutrition: {
      calories: 320,
      protein: 28,
      carbs: 12,
      fat: 18,
      fiber: 4,
      sodium: 680,
    },
    tags: ['Asian', 'Quick', 'High Protein'],
    isCustom: false,
  },
  {
    id: '7',
    name: 'Caesar Salad',
    description: 'Classic Caesar salad with homemade dressing',
    image: undefined,
    cookTime: 0,
    prepTime: 15,
    servings: 4,
    difficulty: 'easy',
    category: 'Lunch',
    ingredients: [
      { id: '1', name: 'Romaine lettuce', amount: '2', unit: 'heads' },
      { id: '2', name: 'Parmesan cheese', amount: '1/2', unit: 'cup' },
      { id: '3', name: 'Croutons', amount: '1', unit: 'cup' },
      { id: '4', name: 'Anchovy fillets', amount: '2', unit: 'pieces' },
      { id: '5', name: 'Garlic', amount: '2', unit: 'cloves' },
      { id: '6', name: 'Lemon juice', amount: '2', unit: 'tbsp' },
      { id: '7', name: 'Dijon mustard', amount: '1', unit: 'tsp' },
      { id: '8', name: 'Olive oil', amount: '1/4', unit: 'cup' },
    ],
    steps: [
      {
        id: '1',
        stepNumber: 1,
        description: 'Wash and dry romaine lettuce, tear into bite-sized pieces',
        duration: 3,
      },
      {
        id: '2',
        stepNumber: 2,
        description: 'Make dressing by blending anchovies, garlic, lemon juice, and mustard',
        duration: 3,
      },
      {
        id: '3',
        stepNumber: 3,
        description: 'Slowly whisk in olive oil until emulsified',
        duration: 2,
      },
      {
        id: '4',
        stepNumber: 4,
        description: 'Toss lettuce with dressing until well coated',
        duration: 2,
      },
      {
        id: '5',
        stepNumber: 5,
        description: 'Add croutons and grated parmesan cheese',
        duration: 2,
      },
      {
        id: '6',
        stepNumber: 6,
        description: 'Serve immediately',
        duration: 1,
      },
    ],
    nutrition: {
      calories: 180,
      protein: 8,
      carbs: 12,
      fat: 12,
      fiber: 3,
      sodium: 420,
    },
    tags: ['Healthy', 'Vegetarian', 'Classic'],
    isCustom: false,
  },
  {
    id: '8',
    name: 'Banana Pancakes',
    description: 'Fluffy pancakes with mashed banana and cinnamon',
    image: undefined,
    cookTime: 15,
    prepTime: 10,
    servings: 4,
    difficulty: 'easy',
    category: 'Breakfast',
    ingredients: [
      { id: '1', name: 'All-purpose flour', amount: '1', unit: 'cup' },
      { id: '2', name: 'Baking powder', amount: '2', unit: 'tsp' },
      { id: '3', name: 'Salt', amount: '1/4', unit: 'tsp' },
      { id: '4', name: 'Milk', amount: '1', unit: 'cup' },
      { id: '5', name: 'Egg', amount: '1', unit: 'large' },
      { id: '6', name: 'Ripe banana', amount: '1', unit: 'piece' },
      { id: '7', name: 'Butter', amount: '2', unit: 'tbsp' },
      { id: '8', name: 'Cinnamon', amount: '1/2', unit: 'tsp' },
    ],
    steps: [
      {
        id: '1',
        stepNumber: 1,
        description: 'Mix flour, baking powder, salt, and cinnamon in a large bowl',
        duration: 2,
      },
      {
        id: '2',
        stepNumber: 2,
        description: 'In another bowl, whisk together milk, egg, and melted butter',
        duration: 2,
      },
      {
        id: '3',
        stepNumber: 3,
        description: 'Mash banana and add to wet ingredients',
        duration: 1,
      },
      {
        id: '4',
        stepNumber: 4,
        description: 'Pour wet ingredients into dry ingredients and stir until just combined',
        duration: 2,
      },
      {
        id: '5',
        stepNumber: 5,
        description: 'Heat a griddle or pan over medium heat',
        duration: 3,
      },
      {
        id: '6',
        stepNumber: 6,
        description: 'Pour 1/4 cup batter for each pancake',
        duration: 1,
      },
      {
        id: '7',
        stepNumber: 7,
        description: 'Cook until bubbles form on surface, then flip and cook until golden',
        duration: 4,
      },
    ],
    nutrition: {
      calories: 200,
      protein: 6,
      carbs: 32,
      fat: 6,
      fiber: 2,
      sugar: 8,
      sodium: 280,
    },
    tags: ['Breakfast', 'Sweet', 'Quick'],
    isCustom: false,
  },
];

// Helper function to get recipe by ID
export const getRecipeById = (id: string): Recipe | undefined => {
  return dummyRecipes.find(recipe => recipe.id === id);
};

// Helper function to get recipes by category
export const getRecipesByCategory = (category: string): Recipe[] => {
  return dummyRecipes.filter(recipe => recipe.category === category);
};

// Helper function to search recipes
export const searchRecipes = (query: string): Recipe[] => {
  const lowercaseQuery = query.toLowerCase();
  return dummyRecipes.filter(recipe => 
    recipe.name.toLowerCase().includes(lowercaseQuery) ||
    recipe.description?.toLowerCase().includes(lowercaseQuery) ||
    recipe.tags?.some(tag => tag.toLowerCase().includes(lowercaseQuery))
  );
};
